# it's a build stage for prod
FROM node:16-alpine as build
WORKDIR /build

COPY ./package.json .
COPY ./package-lock.json .
RUN npm ci --cache .npm
COPY . /build/
RUN npm run build

# this runs a litle nginx instance to serve the app
FROM nginx:alpine as prod
EXPOSE 3000
COPY --from=build /build/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
